### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [ocharles/libsystemd-journal#10]
Hi,

it would help the work of the distribution packagers, and probably your users as well, if your package was part of stackage, which ensures that it is compatible with other haskell packages and provides some free QA. Please consider adding your package to stackage: http://www.stackage.org/authors

Thanks,
Joachim

**Comment by ocharles** [comment]
Thanks for the suggestion, @nomeata - I've filed a request over at https://github.com/fpco/stackage/pull/694
