### ISSUE TITLE
Can this build on Ubuntu?

### ISSUE THREAD

**Issue by chris-martin** [ocharles/libsystemd-journal#16]
I'm trying to get a project building on Travis CI (so, in Ubuntu) and getting this error:

    Configuring libsystemd-journal-1.4.0...
    setup: The pkg-config package 'libsystemd' version >=209 is required but it could not be found.

Do you know what packages are needed to build this project on Ubuntu?

**Comment by jahaynes** [comment]
Using Ubuntu Mate 15.10 here.  It appears to build fine after install `libsystemd-dev`.

**Comment by chris-martin** [comment]
Oh, I see - I just noticed that `libsystemd-dev` isn't actually getting installed in my build because it isn't on the Travis CI package whitelist. Thanks.
