### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage.

### ISSUE THREAD

**Issue by expipiplus1** [ocharles/libsystemd-journal#18]
The documentation for the latest version of this package is missing on Hackage.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by ocharles** [comment]
Thanks for the nudge - documentation is now uploaded. Sorry it took so long!

**Comment by expipiplus1** [comment]
No worries, thanks!
