### ISSUE TITLE
JournalFields should be a multimap

### ISSUE THREAD

**Issue by shlevy** [ocharles/libsystemd-journal#2]
From `sd_journal_send(3)`:

> A variable may be assigned more than one value per entry.

This sample program will create a journal entry that can't be expressed with the current `JournalEntry` type:

``` C
#include <systemd/sd-journal.h>

int main(int argc, char ** argv) {
        sd_journal_send("FOO=bar", "FOO=baz", NULL);
}
```

**Comment by ocharles** [comment]
I'm not sure where I got to with this work, but I'm no longer adding new features to this library, only providing maintenance. If anyone needs this feature, feel free to send a PR and I will happily merge it in.
