### ISSUE TITLE
Dependency version constraints

### ISSUE THREAD

**Issue by defanor** [ocharles/libsystemd-journal#28]
There is this `base < 4.15` constraint, which prevents building with the current GHC (and base package) versions from Debian stable (GHC 9.0.2, base 4.15.1.0), but apparently it can be relaxed, and the package builds fine then. Maybe it can be relaxed even further at once, and along with semigroups (builds fine with 0.20) and unix-bytestring (builds fine with 0.4.0), since those constraints lead to potential unnecessary incompatibilities, too.

**Comment by chris-martin** [comment]
base 4.16 to 4.18 (GHC 9.2 to 9.6) are now supported in the latest release.

**Comment by defanor** [comment]
It is quite a leap; now it is not usable with GHC and base from Debian stable repositories because the range is above the available version, instead of being below.

**Comment by chris-martin** [comment]
Made a metadata revision to `4.5.1` to bump the `base` upper bound to `< 4.17`

**Comment by defanor** [comment]
Thanks!
