### ISSUE TITLE
Export JournalEntry constructor

### ISSUE THREAD

**Issue by soenkehahn** [ocharles/libsystemd-journal#5]
For a testsuite I wanted to write a mock for `openJournal`. This is not possible without the `JournalEntry` constructor.

(Apart from that: What advantages does it have not to expose the constructor?)

@ocharles: Would you be interested in PRs for this (and #4)?

**Comment by TristanCacqueray** [comment]
Is this still necessary? Would using an adapted `openJournal` with a custom data type be sufficient?

**Comment by soenkehahn** [comment]
@TristanCacqueray: Not sure whether this question is for me, but in case it is: I don't know. I'm not using this library anymore. (And I'm not really super invested in getting this fixed anymore. Sorry, that this isn't too helpful...) Should we close the ticket?

**Comment by TristanCacqueray** [comment]
@soenkehahn I'm not sure why the constructors are not exported, and it seems like using an adapter to produce a custom data type for journal entry can work around that limitation. Well if you are no longer using this library, I think you can close the ticket, and perhaps re-open it if needed in the future.

**Comment by soenkehahn** [comment]
Sounds good, thanks!
